### ISSUE TITLE
Allow override Time of Use

### ISSUE THREAD

**Issue by jesserockz** [jesserockz/python-juicenet#1]
- [ ] Have a call to switch to override Time of Use charge settings

**Comment by LorenKeagle** [comment]
Hey there, @jesserockz 

Are you still maintaining this library?  It appears to be used by the juicebox module in HomeAssistant, and I would very much like to be able to trigger the charge override function from an automation script.

I know the API that should be called to set the override flag.  I'm just wondering if I should fork your project or whether you're interested in completing this enhancement.

**Comment by jesserockz** [comment]
Hi @LorenKeagle.

As you can see I have always wanted to create it but just never had the time/forgot about doing it. If your happy to implement it then im happy to accept a PR with the changes and release it.

**Comment by LorenKeagle** [comment]
Seems straightforward enough.  I'm not a node guy, but this should be fairly easy.

**Comment by LorenKeagle** [comment]
Hey @jesserockz,

I've submitted a PR for adding support for setOverride.  If there's any other functionality you think might be useful, I'm happy to continue to work on it.  Otherwise, if we can get this PR merged I will work on getting support added downstream in the HomeAssistant project.

My end goal is to be able to automatically enable my charger during the day when I know I have the additional solar capacity to handle it.  I don't want to dip into the grid if it gets cloudy or my A/C turns on  :-)

**Comment by jesserockz** [comment]
Thanks for that @LorenKeagle 
Do you have a link the the documentation for the API?

**Comment by jesserockz** [comment]
@LorenKeagle I have release 0.1.0 to PyPi 🎉
